name: Akiranya

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/Akiranya.yml'
  schedule:
    - cron: '0 0 */1 * *'

jobs:
  ExcellentCrates-paper:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Akiranya/ExcellentCrates-paper"
      name: "ExcellentCrates"
