name: Auxilor/eco

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  eco:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Auxilor/eco"
  EcoBosses:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Auxilor/EcoBosses"
    
