name: Auxilor/eco

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: "Auxilor/eco"
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16.0'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew shadowJar
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: eco-core/core-plugin/build/libs/*.jar
