name: ds58

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/ds58.yml'
  schedule:
    - cron: '0 0 * * *'

jobs:
  Panilla:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: "ds58/Panilla"
      
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: |
          8
          16
          17
        distribution: 'temurin'
    - name: Run BuildTools
      run: |
        curl -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        "${JAVA_HOME_8_${{ runner.arch }}}"/bin/java -jar BuildTools.jar --rev 1.8.8 --compile craftbukkit
        "${JAVA_HOME_8_${{ runner.arch }}}"/bin/java -jar BuildTools.jar --rev 1.12.2 --compile craftbukkit
        "${JAVA_HOME_8_${{ runner.arch }}}"/bin/java -jar BuildTools.jar --rev 1.13.2 --compile craftbukkit
        "${JAVA_HOME_8_${{ runner.arch }}}"/bin/java -jar BuildTools.jar --rev 1.14.4 --compile craftbukkit
        "${JAVA_HOME_8_${{ runner.arch }}}"/bin/java -jar BuildTools.jar --rev 1.15 --compile craftbukkit
        "${JAVA_HOME_8_${{ runner.arch }}}"/bin/java -jar BuildTools.jar --rev 1.16.1
        "${JAVA_HOME_8_${{ runner.arch }}}"/bin/java -jar BuildTools.jar --rev 1.16.2
        "${JAVA_HOME_8_${{ runner.arch }}}"/bin/java -jar BuildTools.jar --rev 1.16.4
        "${JAVA_HOME_16_${{ runner.arch }}}"/bin/java -jar BuildTools.jar --rev 1.17
        "${JAVA_HOME_17_${{ runner.arch }}}"/bin/java -jar BuildTools.jar --rev 1.18.2
        "${JAVA_HOME_17_${{ runner.arch }}}"/bin/java -jar BuildTools.jar --rev 1.19.2
        "${JAVA_HOME_17_${{ runner.arch }}}"/bin/java -jar BuildTools.jar --rev latest
        
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: "Panilla"
        path: 'target/*.jar'
