name: Gradle Build
on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      target:
        default: 'build/libs/*.jar'
        required: false
        type: string
      name:
        default: 'Artifact'
        required: false
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ inputs.repository }}
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16.0'
        distribution: 'adopt'
    - name: Grant permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew shadowJar
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.target }}
