name: Gradle Build
on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ inputs.repo }}
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16.0'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew shadowJar
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: build/libs/*.jar
