name: Maxlego08

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/Maxlego08.yml'
  schedule:
    - cron: '0 */12 * * *'

jobs:
  zEssentials:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Maxlego08/zEssentials"
      name: "zEssentials"
