name: NEZNAMY

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/NEZNAMY.yml'
  schedule:
    - cron: '0 */6 * * *'

jobs:
  TAB:
    uses: HSGamer/ConstructProjects/.github/workflows/maven-build.yml@main
    with:
      repository: "NEZNAMY/TAB"
      target: "jar/target/*.jar"
      name: "TAB"
