name: Photon

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/Photon.yml'
  schedule:
    - cron: '0 0 * * *'

jobs:
  AACAdditionPro:
    uses: HSGamer/ConstructProjects/.github/workflows/maven-build.yml@main
    with:
      repository: "Photon-GitHub/AACAdditionPro"
      name: "AACAdditionPro"
      java: 17
  AACAdditionPro_8-3-2:
    uses: HSGamer/ConstructProjects/.github/workflows/maven-build.yml@main
    with:
      repository: "Dungjava/AntiCheatAddition"
      name: "AACAdditionPro"
      java: 17
