name: test

on:
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/test.yml'
  schedule:
    - cron: '0 */6 * * *'

jobs:
  MultiverseCore:
    uses: Dungjava/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Piratemajo/Multiverse-Core-Folia"
      target: "build/libs/*.jar"
      name: "Multiverse_Core_Folia"
      java: 11
  MultiverseCoreZeta:
    uses: Dungjava/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "RenYuan-MC/Multiverse-Core_Zeta"
      target: "build/libs/*.jar"
      name: "Multiverse-Core_Zeta"
      java: 11
