name: Trophonix

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/Trophonix.yml'
  schedule:
    - cron: '0 0 * * *'

jobs:
  TradePlus:
    uses: HSGamer/ConstructProjects/.github/workflows/maven-build.yml@main
    with:
      repository: "Trophonix/TradePlus"
      name: "TradePlus"
      java: 16
      os: windows-latest
      commands: |
        $Response = Invoke-WebRequest -Uri "https://www.bencodez.com/job/VotingPlugin/lastSuccessfulBuild/artifact/VotingPlugin/target/VotingPlugin.jar"
        $Stream = [System.IO.StreamWriter]::new('.\res\VotingPlugin.jar', $false, $Response.Encoding)
        try {
          $Stream.Write($Response.Content)
        }
        finally {
          $Stream.Dispose()
        }
