name: Trophonix

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/Trophonix.yml'
  schedule:
    - cron: '0 0 * * *'

jobs:
  TradePlus:
    uses: HSGamer/ConstructProjects/.github/workflows/maven-build.yml@main
    with:
      repository: "Trophonix/TradePlus"
      name: "TradePlus"
      java: 16
      os: windows-latest
      commands: |
        Invoke-WebRequest -Uri "https://www.bencodez.com/job/VotingPlugin/lastSuccessfulBuild/artifact/VotingPlugin/target/VotingPlugin.jar" -OutFile ".\res\VotingPlugin.jar"
        set MAVEN_OPTS="-Xmx2048m --illegal-access=permit"
