name: Trophonix

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/Trophonix.yml'
  schedule:
    - cron: '0 0 * * *'

jobs:
  eco:
    uses: HSGamer/ConstructProjects/.github/workflows/maven-build.yml@main
    with:
      repository: "Trophonix/TradePlus"
      name: "TradePlus"
