name: VolmitSoftware

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/VolmitSoftware.yml'
  schedule:
    - cron: '0 0 * * *'

jobs:
  Iris:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "VolmitSoftware/Iris"
      name: "Iris"
      java: "17"
  Adapt:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "VolmitSoftware/Adapt"
      name: "Adapt"
      java: "17"
  React:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "VolmitSoftware/React"
    - name: Set up JDK
      uses: actions/setup-java@v3.12.0
      with:
        java-version: 17
        distribution: temurin
        cache: gradle
    - name: Build with Gradle
      run: |
        cd ./React
        chmod +x gradlew
        ./gradlew build
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: "React"
        path: "React/build/libs/*.jar"
