name: VolmitSoftware

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/VolmitSoftware.yml'
  schedule:
    - cron: '0 0 * * *'

jobs:
  Iris:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "VolmitSoftware/Iris"
      name: "Iris"
      java: "17"
