name: WonkyPigs

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/WonkyPigs.yml'
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  CosmicVaults_VN:
    uses: HSGamer/ConstructProjects/.github/workflows/maven-build.yml@main
    with:
      repository: "Dungjava/CosmicVaults"
      name: "CosmicVaults_VN"
      java: 17
